server:
  port: 8880
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/yu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
security:
  oauth2:
    client:
      client-id: zuul
      client-secret: 123456
      access-token-uri: http://localhost:8887/oauth/token
      user-authorization-uri: http://localhost:8887/oauth/authorize
      client-authentication-scheme: form
      use-current-uri: false
      pre-established-redirect-uri: /login
    resource:      #这配配置的是服务器的地址
      token-info-uri: 'http://127.0.0.1:8887/oauth/check_token'
#      user-info-uri: '@user.info.url@'     
#    sso:
      ## 这个地址是sso校验auth_code的地址
#      login-path: '/a/login'
zuul:
  add-host-header: true
  ## 默认情况下，zuul 会将 authorization cookie set-cookie 这三个敏感的header不作为转发对象
  ## 在这里重新定义
#  sensitive-headers:
#  - cookie
#  - set-cookie
  include-debug-header: true
#  网管路由配置
  routes:
    data: ## 数据中心的代理
      strip-prefix: true
      path: '/d/data/**'
      url: 'http://127.0.0.1:8081/'
    files: ## 文件服务器的代理
      strip-prefix: true
      path: '/d/files/**'
      url: 'http://127.0.0.1:8886/files'
    uap: ## 用户服务器的代理
      path: '/u/**'
      strip-prefix: true
      url: 'http://127.0.0.1:8887/'

    