server:
  port: 8099
spring:
  main:
    allow-bean-definition-overriding: true
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/